const GET_BOOKS_LOADING: string = "GET_BOOKS_LOADING";
const GET_BOOKS_SUCCESS: string = "GET_BOOKS_SUCCESS";
const GET_BOOKS_ERROR: string = "GET_BOOKS_ERROR";
export { GET_BOOKS_LOADING, GET_BOOKS_SUCCESS, GET_BOOKS_ERROR };
