const GET_BOOKS_LOADING: string = "GET_BOOKS_LOADING";
const GET_BOOKS_SUCCESS: string = "GET_BOOKS_SUCCESS";
const GET_BOOKS_ERROR: string = "GET_BOOKS_ERROR";
const GET_AUTHOR_LOADING = "GET_AUTHOR_LOADING";
const GET_AUTHOR_SUCCESS = "GET_AUTHOR_SUCCESS";
const GET_AUTHOR_ERROR = "GET_AUTHOR_ERROR";
const RESET_DATA: string = "RESET_DATA";
export {
  GET_BOOKS_LOADING,
  GET_BOOKS_SUCCESS,
  GET_BOOKS_ERROR,
  RESET_DATA,
  GET_AUTHOR_LOADING,
  GET_AUTHOR_SUCCESS,
  GET_AUTHOR_ERROR,
};
